import json,urllib.parse

def Aashu32(Aashu1): return json.dumps(Aashu1,ensure_ascii=False,indent=2)
def Aashu31(Aashu1):
 Aashu2=urllib.parse.urlsplit(Aashu1['url']);Aashu3=Aashu2.path or '/';Aashu4='?'+Aashu2.query if Aashu2.query else '';Aashu5=[f'{Aashu6}: {Aashu7}' for Aashu6,Aashu7 in Aashu1['headers'].items()];return Aashu1['method']+' '+Aashu3+Aashu4+' HTTP/1.1\nHost: '+Aashu2.netloc+'\n'+'\n'.join(Aashu5)+(('\n\n'+Aashu1['body']) if Aashu1['body'] is not None else '')
def Aashu30(Aashu1): return 'curl -X '+Aashu1['method']+' '+repr(Aashu1['url'])+' '+ ' '.join('-H '+repr(f'{Aashu2}: {Aashu3}') for Aashu2,Aashu3 in Aashu1['headers'].items())+((' --data '+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')
def Aashu29(Aashu1): return 'wget --method='+Aashu1['method']+' '+repr(Aashu1['url'])+' '+' '.join('--header='+repr(f'{Aashu2}: {Aashu3}') for Aashu2,Aashu3 in Aashu1['headers'].items())
def Aashu28(Aashu1): return 'Invoke-WebRequest -Uri '+repr(Aashu1['url'])+' -Method '+Aashu1['method']+((' -Headers '+repr(Aashu1['headers'])) if Aashu1['headers'] else '')+((' -Body '+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')
def Aashu27(Aashu1): return "use HTTP::Tiny;my Aashu1=HTTP::Tiny->new;my Aashu2=Aashu1->request("+repr(Aashu1['method'])+','+repr(Aashu1['url'])+',\'{headers=>'+repr(Aashu1['headers'])+((',content=>'+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')+'}\');print $Aashu2->{content};'
def Aashu26(Aashu1): return "local http=require('socket.http');local Aashu1={};local Aashu2="+repr(Aashu1['body'] or '')+";http.request{url="+repr(Aashu1['url'])+',method='+repr(Aashu1['method'])+',headers='+repr(Aashu1['headers'])+',source=ltn12.source.string(Aashu2),sink=ltn12.sink.table(Aashu1)};print(table.concat(Aashu1))'
def Aashu25(Aashu1): return 'library(httr2)\nAashu1<-request('+repr(Aashu1['url'])+')|>req_method('+repr(Aashu1['method'])+')'+(('|>req_headers('+','.join(repr(Aashu2)+'='+repr(Aashu3) for Aashu2,Aashu3 in Aashu1['headers'].items())+')') if Aashu1['headers'] else '')+(('|>req_body_raw('+repr(Aashu1['body'])+')') if Aashu1['body'] is not None else '')+'|>req_perform()'
def Aashu24(Aashu1): return "import 'package:http/http.dart' as http;void main()async{var Aashu1=http.Request("+repr(Aashu1['method'])+',Uri.parse('+repr(Aashu1['url'])+'));Aashu1.headers.addAll('+repr(Aashu1['headers'])+');'+(('Aashu1.body='+repr(Aashu1['body'])+';') if Aashu1['body'] is not None else '')+'var Aashu2=await http.Client().send(Aashu1);print(await Aashu2.stream.bytesToString());}'
def Aashu23(Aashu1): return 'import Foundation\nvar Aashu1=URLRequest(url:URL(string:'+json.dumps(Aashu1['url'])+')!)\nAashu1.httpMethod='+json.dumps(Aashu1['method'])+'\n'+''.join('Aashu1.setValue('+json.dumps(Aashu3)+',forHTTPHeaderField:'+json.dumps(Aashu2)+')\n' for Aashu2,Aashu3 in Aashu1['headers'].items())+(('Aashu1.httpBody='+json.dumps(Aashu1['body'])+'.data(using:.utf8)\n') if Aashu1['body'] is not None else '')+'URLSession.shared.dataTask(with:Aashu1){Aashu2,_,_ in print(String(data:Aashu2 ?? Data(),encoding:.utf8) ?? "")}.resume()'
def Aashu22(Aashu1): return 'val Aashu1=Request.Builder().url('+json.dumps(Aashu1['url'])+').method('+json.dumps(Aashu1['method'])+',null).build();OkHttpClient().newCall(Aashu1).execute().use{println(it.body?.string())}'
def Aashu21(Aashu1): return 'use reqwest::blocking::Client;fn main(){let Aashu1=Client::new().request(reqwest::Method::'+Aashu1['method']+','+json.dumps(Aashu1['url'])+').send().unwrap();println!("{}",Aashu1.text().unwrap());}'
def Aashu20(Aashu1): return 'curl_easy_setopt(curl_easy_init(),CURLOPT_CUSTOMREQUEST,'+json.dumps(Aashu1['method'])+');curl_easy_setopt(curl_easy_init(),CURLOPT_URL,'+json.dumps(Aashu1['url'])+');'
def Aashu19(Aashu1): return '#include <curl/curl.h>\nint main(){CURL*Aashu1=curl_easy_init();curl_easy_setopt(Aashu1,CURLOPT_CUSTOMREQUEST,'+json.dumps(Aashu1['method'])+');curl_easy_setopt(Aashu1,CURLOPT_URL,'+json.dumps(Aashu1['url'])+');curl_easy_perform(Aashu1);curl_easy_cleanup(Aashu1);}'
def Aashu18(Aashu1): return 'var Aashu1=new RestSharp.RestClient('+repr(Aashu1['url'])+');var Aashu2=new RestSharp.RestRequest();Aashu2.Method=RestSharp.Method.'+Aashu1['method'].title()+';'+''.join('Aashu2.AddHeader('+repr(Aashu3)+','+repr(Aashu4)+');' for Aashu3,Aashu4 in Aashu1['headers'].items())+'var Aashu3=Aashu1.Execute(Aashu2);Console.WriteLine(Aashu3.Content);'
def Aashu17(Aashu1): return 'OkHttpClient Aashu1=new OkHttpClient();Request Aashu2=new Request.Builder().url('+json.dumps(Aashu1['url'])+').build();Response Aashu3=Aashu1.newCall(Aashu2).execute();System.out.println(Aashu3.body().string());'
def Aashu16(Aashu1): return '$.ajax({url:'+json.dumps(Aashu1['url'])+',type:'+json.dumps(Aashu1['method'])+',headers:'+json.dumps(Aashu1['headers'])+',data:'+json.dumps(Aashu1['body'])+',success:console.log});'
def Aashu15(Aashu1): return 'req,err:=Req.new('+repr(Aashu1['url'])+');resp,err=req:'+Aashu1['method'].lower()+'();IO.puts(resp.body)'
def Aashu14(Aashu1): return 'import aiohttp,asyncio\nasync def Aashu1():\n async with aiohttp.ClientSession() as Aashu2:\n  async with Aashu2.request('+repr(Aashu1['method'])+','+repr(Aashu1['url'])+',headers='+repr(Aashu1['headers'])+',data='+repr(Aashu1['body'])+') as Aashu3: print(await Aashu3.text())\nasyncio.run(Aashu1())'
def Aashu13(Aashu1):
 Aashu2=json.dumps(Aashu1['url']);Aashu3=json.dumps(Aashu1['method']);Aashu4=json.dumps(Aashu1['headers']);Aashu5=json.dumps(Aashu1['body']) if Aashu1['body'] is not None else 'undefined';return 'const Aashu1=async()=>{const Aashu2=await fetch('+Aashu2+',{method:'+Aashu3+',headers:'+Aashu4+',body:'+Aashu5+'});console.log(await Aashu2.text())};Aashu1();'
def Aashu12(Aashu1): return 'fetch('+json.dumps(Aashu1['url'])+', {method:'+json.dumps(Aashu1['method'])+',headers:'+json.dumps(Aashu1['headers'])+',body:'+(json.dumps(Aashu1['body']) if Aashu1['body'] is not None else 'undefined')+'}).then(Aashu1=>Aashu1.text()).then(console.log)'
def Aashu11(Aashu1): return 'const axios=require("axios");axios.request({method:'+json.dumps(Aashu1['method'])+',url:'+json.dumps(Aashu1['url'])+',headers:'+json.dumps(Aashu1['headers'])+',data:'+(json.dumps(Aashu1['body']) if Aashu1['body'] is not None else 'undefined')+'}).then(Aashu1=>console.log(Aashu1.data));'
def Aashu10(Aashu1):
 Aashu2=urllib.parse.urlsplit(Aashu1['url']);Aashu3=Aashu2.hostname or '';Aashu4=Aashu2.port or (443 if Aashu2.scheme=='https' else 80);Aashu5=Aashu2.path or '/';Aashu6='?'+Aashu2.query if Aashu2.query else '';Aashu7='https' if Aashu2.scheme=='https' else 'http';return 'const http=require('+repr(Aashu7)+');const Aashu1={hostname:'+repr(Aashu3)+',port:'+str(Aashu4)+',path:'+repr(Aashu5+Aashu6)+',method:'+repr(Aashu1['method'])+',headers:'+json.dumps(Aashu1['headers'])+'};const Aashu2=http.request(Aashu1,Aashu3=>{let Aashu4="";Aashu3.on("data",Aashu5=>Aashu4+=Aashu5);Aashu3.on("end",()=>console.log(Aashu4));});Aashu2.on("error",console.error);'+(('Aashu2.write('+json.dumps(Aashu1['body'])+');') if Aashu1['body'] is not None else '')+'Aashu2.end();'
def Aashu9(Aashu1): return 'import java.net.URI;import java.net.http.*;public class Aashu1{public static void main(String[]Aashu2)throws Exception{HttpRequest Aashu3=HttpRequest.newBuilder(URI.create('+json.dumps(Aashu1['url'])+'))'+''.join('.header('+json.dumps(Aashu4)+','+json.dumps(Aashu5)+')' for Aashu4,Aashu5 in Aashu1['headers'].items())+'.method('+json.dumps(Aashu1['method'])+','+('HttpRequest.BodyPublishers.ofString('+json.dumps(Aashu1['body'])+')' if Aashu1['body'] is not None else 'HttpRequest.BodyPublishers.noBody()')+').build();System.out.println(HttpClient.newHttpClient().send(Aashu3,HttpResponse.BodyHandlers.ofString()).body());}}'
def Aashu8(Aashu1): return 'using System;using System.Net.Http;using System.Threading.Tasks;class Aashu1{static async Task Main(){using var Aashu2=new HttpClient();using var Aashu3=new HttpRequestMessage(new HttpMethod('+json.dumps(Aashu1['method'])+'),'+json.dumps(Aashu1['url'])+');'+''.join('Aashu3.Headers.TryAddWithoutValidation('+json.dumps(Aashu4)+','+json.dumps(Aashu5)+');' for Aashu4,Aashu5 in Aashu1['headers'].items())+(('Aashu3.Content=new StringContent('+json.dumps(Aashu1['body'])+');') if Aashu1['body'] is not None else '')+'var Aashu4=await Aashu2.SendAsync(Aashu3);Console.WriteLine(await Aashu4.Content.ReadAsStringAsync());}}'
def Aashu7(Aashu1): return '<?php $Aashu1=curl_init('+repr(Aashu1['url'])+');curl_setopt_array($Aashu1,[CURLOPT_CUSTOMREQUEST=>'+repr(Aashu1['method'])+',CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>'+repr([f'{Aashu2}: {Aashu3}' for Aashu2,Aashu3 in Aashu1['headers'].items()])+((',CURLOPT_POSTFIELDS=>'+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')+']);echo curl_exec($Aashu1);curl_close($Aashu1);'
def Aashu6(Aashu1): return '<?php $Aashu1=new \\GuzzleHttp\\Client();$Aashu2=$Aashu1->request('+repr(Aashu1['method'])+','+repr(Aashu1['url'])+',[\'headers\'=>'+repr(Aashu1['headers'])+((',\'body\'=>'+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')+']);echo $Aashu2->getBody();'
def Aashu5(Aashu1): return "require 'net/http';Aashu1=URI("+repr(Aashu1['url'])+");Aashu2=Net::HTTP::GenericRequest.new("+repr(Aashu1['method'])+',true,true,Aashu1.request_uri);'+''.join('Aashu2['+repr(Aashu3)+']='+repr(Aashu4)+';' for Aashu3,Aashu4 in Aashu1['headers'].items())+"Aashu3=Net::HTTP.new(Aashu1.host,Aashu1.port);Aashu3.use_ssl=Aashu1.scheme=='https';puts Aashu3.request(Aashu2).body"
def Aashu4(Aashu1): return 'package main\nimport("fmt";"io";"net/http";"strings")\nfunc main(){Aashu1,_:=http.NewRequest('+json.dumps(Aashu1['method'])+','+json.dumps(Aashu1['url'])+',strings.NewReader('+json.dumps(Aashu1['body'] or '')+'));'+''.join('Aashu1.Header.Set('+json.dumps(Aashu2)+','+json.dumps(Aashu3)+');' for Aashu2,Aashu3 in Aashu1['headers'].items())+'Aashu2,_:=http.DefaultClient.Do(Aashu1);defer Aashu2.Body.Close();Aashu3,_:=io.ReadAll(Aashu2.Body);fmt.Print(string(Aashu3))}'
def Aashu3(Aashu1): return 'import urllib.request\nAashu1=urllib.request.Request('+json.dumps(Aashu1['url'])+',data='+('('+json.dumps(Aashu1['body'])+').encode()' if Aashu1['body'] is not None else 'None')+',headers='+json.dumps(Aashu1['headers'])+',method='+json.dumps(Aashu1['method'])+')\nprint(urllib.request.urlopen(Aashu1).read().decode())'
def Aashu2(Aashu1): return 'import http.client,urllib.parse\nAashu1=urllib.parse.urlparse('+repr(Aashu1['url'])+')\nAashu2=http.client.HTTPSConnection(Aashu1.netloc) if Aashu1.scheme=="https" else http.client.HTTPConnection(Aashu1.netloc)\nAashu2.request('+repr(Aashu1['method'])+',Aashu1.path or "/"'+((',body='+repr(Aashu1['body'])) if Aashu1['body'] is not None else '')+',headers='+repr(Aashu1['headers'])+')\nprint(Aashu2.getresponse().read().decode())'
def Aashu1(Aashu1): return Aashu3(Aashu1)
Aashu33={1:('Python Requests',Aashu1),2:('Python http.client',Aashu2),3:('Python urllib.request',Aashu3),4:('Go net/http',Aashu4),5:('Ruby Net::HTTP',Aashu5),6:('PHP Guzzle',Aashu6),7:('PHP cURL',Aashu7),8:('C# HttpClient',Aashu8),9:('Java HttpClient',Aashu9),10:('Node.js http',Aashu10),11:('JavaScript Axios',Aashu11),12:('JavaScript Fetch',Aashu12),13:('TypeScript Fetch',Aashu13),14:('Python aiohttp',Aashu14),15:('Elixir Req',Aashu15),16:('JavaScript jQuery',Aashu16),17:('Java OkHttp',Aashu17),18:('C# RestSharp',Aashu18),19:('C++ libcurl',Aashu19),20:('C libcurl',Aashu20),21:('Rust reqwest',Aashu21),22:('Kotlin OkHttp',Aashu22),23:('Swift URLSession',Aashu23),24:('Dart http',Aashu24),25:('R httr2',Aashu25),26:('Lua LuaSocket',Aashu26),27:('Perl HTTP::Tiny',Aashu27),28:('PowerShell',Aashu28),29:('Wget',Aashu29),30:('Bash curl',Aashu30),31:('Raw HTTP',Aashu31),32:('JSON',Aashu32)}
def Aashu34(Aashu1): return {Aashu2:Aashu3(Aashu1) for Aashu2,(_,Aashu3) in Aashu33.items()}
